services:
  - type: web
    name: luz-fusion-5
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: LUZ_UNIVERSE_PASSWORD
        value: Tommyboy3018
      - key: NODE_ENV
        value: production
